'use client';

import Link from 'next/link';

export default function DocsPage() {
  return (
    <main className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 py-20">
      <div className="max-w-4xl mx-auto px-6">
        {/* Header */}
        <div className="text-center mb-16">
          <h1 className="text-5xl font-black text-gray-900 mb-4">Documentation</h1>
          <p className="text-xl text-gray-600">Learn how to create amazing personalized stories for your child</p>
        </div>

        <div className="bg-white rounded-2xl shadow-xl p-12 space-y-8">
          {/* Getting Started */}
          <section>
            <h2 className="text-3xl font-bold text-gray-900 mb-4">Getting Started</h2>
            <p className="text-gray-700 mb-4">
              Kidz Story Magic makes it easy to create personalized, AI-powered storybooks for children. Follow these steps to get started:
            </p>
            <ol className="list-decimal list-inside space-y-2 text-gray-700">
              <li>Sign up for a free account</li>
              <li>Click "Create Story Now" to start the wizard</li>
              <li>Fill in your child's details and preferences</li>
              <li>Generate your personalized story</li>
              <li>Download or share your story</li>
            </ol>
          </section>

          {/* Features */}
          <section>
            <h2 className="text-3xl font-bold text-gray-900 mb-4">Key Features</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="bg-blue-50 p-6 rounded-lg">
                <h3 className="text-xl font-bold text-blue-900 mb-2">✨ Personalized Stories</h3>
                <p className="text-gray-700">Each story is customized with your child's name and interests</p>
              </div>
              <div className="bg-blue-50 p-6 rounded-lg">
                <h3 className="text-xl font-bold text-blue-900 mb-2">🎨 Multiple Themes</h3>
                <p className="text-gray-700">Choose from 10+ exciting themes: Adventure, Space, Fairy Tales, and more</p>
              </div>
              <div className="bg-blue-50 p-6 rounded-lg">
                <h3 className="text-xl font-bold text-blue-900 mb-2">🤖 AI Illustrations</h3>
                <p className="text-gray-700">Professional quality illustrations generated by AI</p>
              </div>
              <div className="bg-blue-50 p-6 rounded-lg">
                <h3 className="text-xl font-bold text-blue-900 mb-2">📚 Flexible Lengths</h3>
                <p className="text-gray-700">Choose 10, 20, or 30 pages for your story</p>
              </div>
              <div className="bg-blue-50 p-6 rounded-lg">
                <h3 className="text-xl font-bold text-blue-900 mb-2">📥 Multiple Formats</h3>
                <p className="text-gray-700">Download as PDF or share directly with family</p>
              </div>
              <div className="bg-blue-50 p-6 rounded-lg">
                <h3 className="text-xl font-bold text-blue-900 mb-2">🎯 Age-Appropriate</h3>
                <p className="text-gray-700">Content tailored for ages 0-12</p>
              </div>
            </div>
          </section>

          {/* FAQ */}
          <section>
            <h2 className="text-3xl font-bold text-gray-900 mb-4">Frequently Asked Questions</h2>
            <div className="space-y-4">
              <div className="border-l-4 border-blue-600 pl-4">
                <h3 className="text-lg font-bold text-gray-900">How long does it take to generate a story?</h3>
                <p className="text-gray-700 mt-2">Typically 2-5 minutes depending on page count and complexity</p>
              </div>
              <div className="border-l-4 border-blue-600 pl-4">
                <h3 className="text-lg font-bold text-gray-900">Can I customize the story theme?</h3>
                <p className="text-gray-700 mt-2">Yes! We offer 10+ pre-made themes, plus a custom option</p>
              </div>
              <div className="border-l-4 border-blue-600 pl-4">
                <h3 className="text-lg font-bold text-gray-900">What age groups do you support?</h3>
                <p className="text-gray-700 mt-2">We support children ages 0-12 with age-appropriate content</p>
              </div>
              <div className="border-l-4 border-blue-600 pl-4">
                <h3 className="text-lg font-bold text-gray-900">Can I download stories as PDF?</h3>
                <p className="text-gray-700 mt-2">Yes! PDF download is included with all stories</p>
              </div>
            </div>
          </section>

          {/* Support */}
          <section className="bg-blue-50 p-8 rounded-lg">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Need Help?</h2>
            <p className="text-gray-700 mb-4">
              Our support team is here to help! Email us at{' '}
              <a href="mailto:support@kidzstorymagic.com" className="text-blue-600 font-semibold hover:underline">
                support@kidzstorymagic.com
              </a>
            </p>
          </section>
        </div>

        {/* CTA */}
        <div className="text-center mt-12">
          <Link
            href="/auth/signup"
            className="inline-block px-8 py-4 bg-blue-600 text-white rounded-xl font-bold text-lg hover:bg-blue-700 transition-colors shadow-lg"
          >
            Get Started Free
          </Link>
        </div>
      </div>
    </main>
  );
}
